
name: build tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Install actions/checkout@v2
      uses: actions/checkout@v2

    - name: Install actions/setup-python@v2 for ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade scapy[basic] psutil ouilookup

    - name: flake8 lint
      run: |
        python -m pip install --upgrade flake8
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        # https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
        flake8 ./src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 ./src --count --exit-zero --max-complexity=20 --max-line-length=120 --statistics

    - name: python setup.py clean build
      run: |
        python -m pip install --upgrade wheel setuptools
        python setup.py clean build

    - name: pytest
      run: |
        python -m pip install --upgrade pytest
        pytest

    - name: python setup.py install
      run: |
        python setup.py install

    - name: arpwitch --version
      run: |
        arpwitch --version
